students:
    path:     /api/student/getAll
    defaults:
        _controller: FormerDUTStudentsBundle:Api:getAllStudents
    methods:  [GET]

student:
    path:     /api/student/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Api:getStudent
    methods:  [GET]
    requirements:
        id: \d+

add_student:
    path:     /api/student/add
    defaults: 
        _controller: FormerDUTStudentsBundle:Api:addStudent
    methods:  [POST]
    
delete_student:
    path:     /api/student/delete
    defaults: 
        _controller: FormerDUTStudentsBundle:Api:deleteStudent
    methods:  [GET]
    requirements:
        id: \d+
    
edit_student:
    path:     /api/student/edit/{id}
    defaults: 
        _controller: FormerDUTStudentsBundle:Api:editStudent
    methods:  [PUT]
    requirements: 
        id: \d+

send_mail:
    path: /api/sendmail
    defaults:
        _controller: FormerDUTStudentsBundle:Api:sendMail
