<?php

namespace FormerDUTStudentsBundle\Repository;

/**
 * CredentialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CredentialsRepository extends \Doctrine\ORM\EntityRepository
{
}
